openapi: "3.0.0"
info:
  version: "0.0.1"
  title: Inventory Avails Schemas
  description: Inventory Avails Schemas, based on TIP 4.0.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    inventoryAvailsBuyerObject:
      required:
        - transactionHeader
        - dateSubmitted
        - buyer
        - dateStart
        - dateEnd
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Buyer Submit Date for Inventory
          type: string
          format: date-time
        dueDate:
          description: Due Date for Inventory Information
          type: string
          format: date-time
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        availRequest:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        contractInterval:
          $ref: 'commonSchemas.yaml#/components/schemas/DayOfWeek'
        Genre:
          description: Desired list of genres names to use for filtering selling titles
          type: array
          items:
            type: string #TODO any constraints on this?
        salesElements:
          description: Desired list of selling title names being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        product:
          description: Desired list of selling title names being requested
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Product'
        timeFrame:
          description: Start and End Time(s) for desired inventory
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeWindow'
        daypart:
          description: Desired list of dayparts
          type: array
          items:
            type: string #TODO any constraints on this?
        inventoryTypes:
          description: Desired list of inventory Types
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        maxRate:
          description: Float Max spend requirements in unit rates by inventory type
          type: number
          format: float # TODO any constraints on this?
        currency:
          description: String	Currency Code (ISO  Code)
          type: string # TODO is this expected in ISO 4217 standard?
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        audiences:
          description: Audience details; multiple arrays of of audience segments may be included in the request
          type: array
          items:
            $ref: '#/components/schemas/AudienceObject'
    inventoryAvailsSellerObject:
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        rateCardName:
          description: Seller's Rate Card reference name
          type: string
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        availWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElement'
        salesElementGroups:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementGroup'
      required:
        - transactionHeader
        - dateSubmitted
        - buyer
        - availWindow
        - mediaOutlets
    AudienceObject:
      type: object
      properties:
        audienceSegment:
          $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
        audienceMetric:
          $ref: 'commonSchemas.yaml#/components/schemas/PricingMetric' 
  

