openapi: "3.0.0"
info:
  version: "4.2.0"
  title: Inventory Avails Schemas
  description: Inventory Avails Schemas, based on TIP 4.2.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    inventoryAvailsBuyerRequestObject:
      description: Allows the Buyer as campaign planning to initiate an inventory Request to the Seller
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          description: Buyer Submit Date for Inventory
          type: string
          format: date
        dueDate:
          description: Due Date for Inventory Information
          type: string
          format: date
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        timePeriods:
          $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        guidelines:
          $ref: 'commonSchemas.yaml#/components/schemas/Guideline'
        political:
          description: Indicates if request for inventory requires rates to support political 
          type: boolean
        inventoryTypes:
          description: Desired list of inventory Types
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        maxRate:
          description: Float Max spend requirements in unit rates by inventory type
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string
        audienceSegments:
          description: Audience details; multiple arrays of of audience segments may be included in the request
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
        pricingMetricOptions:
          description: an optional array of applicable/required pricing metrics
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/PricingMetricOption'
      required:
        - transactionHeader
        - dateSubmitted
        - mediaOutlet
        - timePeriods
        - political
        - audienceSegments
    inventoryAvailsSellerResponseObject:
      description: Allows the Seller to post to the buyer their catalog of selling products, pricing and audience information
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        dateSubmitted:
          type: string
          format: date
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        rateCard:
          $ref: 'commonSchemas.yaml#/components/schemas/RateCard'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        political:
          description: Indicates if request for inventory requires rates to support political 
          type: boolean
        mediaOutlets:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        audienceSegments:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegmentDetail'
        availWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        salesElements:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElement'
        salesElementGroups:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/SalesElementGroup'
      required:
        - transactionHeader
        - dateSubmitted
        - mediaOutlets
        - availWindow
        - salesElements
