openapi: "3.0.0"
info:
  title: Invoice Schema
  version: 1.0.0.
  description: Invoice Schema, Based on TIP 4.0 Working Draft
  termsOfService: http://placeholderdomain.io/terms/,
  contact: 
    name: MIT
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {} 
components: 
  schemas: 
    invoiceObject: 
      required: 
      - transactionHeader
      - referenceId
      - invoiceDate
      - calendarType
      - billingCycle
      - billingGranularity
      - startDate
      - endDate
      - buyer
      - advertiser
      - buylineCashTrade
      - grossAmount
      - commission
      - totalNetDollars
      - remittanceInfo
      properties:
        transactionHeader: 
          $ref: 'commonSchemas.yaml#/components/schemas/transactionHeader'
        referenceId:
          description: Information grouping all reference ids and their source that are associated to the invoice
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/referenceIds'
        invoiceDate:
          description: Date in which the original invoice was generated
          type: string
          format: date
        invoiceRevisionDate:
          description: Required for Invoice Revision – Date in which the invoice revision was generated
          type: string
          format: date
        calenderType:
          description: The invoice calendar type
          type: string
          enum: [Broadcast, Calendar]
        billingCycle:
          description: The invoice billing cycle
          type: string
          enum: [Monthy, Weekly]
        billingGranularity:
          description: The invoice billing granilarity
          type: string
          enum: [Order, Brand, InsertionOrder]
        dueDate:
          description: Date in which payment is due on invoice
          type: string
          format: date
        startDate:
          description: First broadcast date valid for the invoice period
          type: string
          format: date
        endDate:
          description: Last broadcast date valid for the invoice period
          type: string
          format: date
        businessType:
          description: Seller-defined type of business
          type: string
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/buyer'
        localNational:
          type: string
          enum: [Local, National]
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/advertiser'
        contact:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/contact'
        buylineCashTrade:
          description: Revenue Type associated to the order
          type: string
          enum: [Cash, Barter, Trade]
        grossAmount:
          description: Total gross dollar for the invoice
          type: number
          format: float
        commission:
          description: Seller commission dollars
          type: number
          format: float
        salesTax:
          description: Sales Tax in USD applied to any elements on the invoice
          type: number
          format: float
        totalNetDollars:
          description: Total net dollars for all units with the invoice (grossamount - commission)
          type: number
        remittanceInfo:
          $ref: 'commonSchemas.yaml#/components/schemas/remittanceInfo'
        externalComment:
          description: free form text for comments
          type: string
        lineDetails:
          description: Line details array of lines
          type: array
          items:
            type: object
            required:
              - buyLineIDReference
              - unitType
              - mediaOutlet
              - product
              - salesElement
              - lineStartDate
              - lineEndDate
              - length
            properties:
              buyLineIDReference:
                description: Seller's Line information (add buyer identifier make optional) 
                type: string
              buyLineIDName:
                description:  Name associated to the line
                type: string
              unitType:
                description: Type of invoice units
                type: string
                enum: [Units, Impressions, NonAirTime]
              pricingMetric:
                $ref: 'commonSchemas.yaml#/components/schemas/pricingMetric'
              totalUnits:
                description: Total number of unequivalized units or impressions (based on invoice's unit type) within the start and end date
                type: number
              mediaOutlet:
                $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
              brand:
                $ref: 'commonSchemas.yaml#/components/schemas/brand'
              product:
                $ref: 'commonSchemas.yaml#/components/schemas/product'
              salesElement:
                description: Sales Element Name
                type: string
              Program:
                description: Program Name
                type: string
              cpeCode:
                $ref: 'commonSchemas.yaml#/components/schemas/cpeCode'
              timeFrame:
                type: array
                items:
                  $ref: 'commonSchemas.yaml#/components/schemas/timeFrame'
              billableRevenue:
                description: Rate's Billable revenue type
                type: string
                enum: [Booked, Actuals]
              rate:
                type: number
                format: float
              lineStartDate:
                description: start date of line
                type: string
                format: startDate
              lineEndDate:
                description: end date of line
                type: string
                format: date
              inventoryType:
                description: Inventory Type associated to unit  (Further Define in order to support cross 
                type: string
                enum: [Commercial, Interstitial, Billboard]
              length:
                description: Length of commercial unit
                type: integer
              unitDetails:
                description: Array of unit details, applicable only when UnitType=Units
                type: array
                items:
                  type: object
                  required:
                    - unitId
                  properties:
                    unitId:
                      description: Seller generated unique number, required
                      type: string
                    adId:
                      type: string
                    broadcastDate:
                      $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'
                    podPosition:
                      type: string
                      enum: [First, Middle, Last]
                    linkType:
                      type: string
                      enum: [Billboard, Piggyback, Bookend, Sponsorship, Package]
                    linkNum:
                      type: integer
                    linkSeq:
                      type: integer
                    Preempt:
                      type: boolean
                    Makegood: 
                      type: boolean
                    ADU:
                      type: boolean
                    bonus:
                      type: boolean
                    rate:
                      type: number
                      format: float
                    credit:
                      type: boolean
                    adjustmentReason:
                      type: string
                    comment:
                      type: string   
                    childUnitDetails:
                      description: Child unit details for parent unit to support Mirror, Audience Network, Diginet or other forms of "child" units
                      type: array
                      items:
                        type: object
                        required:
                          - parentUnitId
                          - unitId
                        properties:
                          ParentUnitId:
                            type: string
                          unitId:
                            type: string
                          mediaOutlet:
                            $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
                          rate:
                            type: number
                            format: float
                          adId:
                            type: string
                          preempt:
                            type: boolean
                          makegood: 
                            type: boolean
                          ADU:
                            type: boolean
                          credit:
                            type: boolean
                          adjustmentReason:
                            type: string
                          broadcastDate:
                            $ref: 'commonSchemas.yaml#/components/schemas/broadcastDate'