openapi: "3.0.0"
info:
  title: RFP Schema
  version: 4.2.0
  description: RFP Schema, Based on TIP 4.0 Working Draft
  termsOfService: http://placeholderdomain.io/terms/
  contact: 
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT

paths: {}

components:
  schemas:
    rfpRequestObject:
      description: >-
        Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goals and overalll terms
      type: object
      properties:
        transactionHeader:          
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          description: Information pertaining to all the ids and their sources that are associated to the RFP;  RFP ID is required
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        dateSubmitted:
          description: Buyer submit date for the RFP
          type: string
          format: date
        dueDate:
          description: Due date for the response
          type: string
          format: date
        buyer:          
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'       
        advertiser:          
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        budget:
          description: Overall total budget for the RFP
          type: number
        comission:
          description: Buyer comission percentage amount
          type: number
        timePeriodPreferences:
          description: >-
            array of date-time windows of interest to the buyer, 
            the array must at least contain one item
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/TimeWindow'
          minItems: 1
        marketPreferences:
          description: List of market preferences (AND) "<Market Name>"
          type: array
          items:
            type: string
        audiencePreferences:
          description: List of audience preferences (AND) "<Demo Name>"
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudienceSegment'
        unitlengthPreferences:
          description: List of unit length preferences (AND) Unit Length in seconds
          type: array
          items:
            type: integer
        guidelines:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/GuideLine'
        objective:
          description: KPI of the overall campaign
          type: string
        comments:
          description: Additional information
          type: string
        campaignGoals:
          description: Goal details
          type: array
          items:
            $ref: '#/components/schemas/CampaignGoal'
      required:
        - transactionHeader
        - referenceIds
        - dateSubmitted
        - advertiser
        - contacts
        - timePeriodPreferences
    CampaignGoal:      
      type: object
      properties:
        distributionType:
          description: Goal type elements
          type: string
          enum: [MediaOutlet Type, Daypart, Market, Quarter, Week]
        distributionMethod:
          description: Distibution method elements
          type: string
          enum: [Impressions, GRPs, Units, Budget]
        distributionName:
          description: Name of goal
          type: string
        distribution:
          type: string
          enum:
            - Percentage
            - Exact
        distributionValue:
          description: Distribution values in percentage or exact value
          type: number
          format: float
        distributionOrder:
          description: Only populate when multiple distributions types are defined. Defines the nesting order for the distributions
          type: integer
          minimum: 0
        distributionOrderParent:
          description: Only populate when multiple distributions types are defined; defines the parent when there are multiple nesting orders 
          type: integer
          nullable: true
      required:
        - distributionType
        - distributionMethod
        - distributionName
        - distribution 
        - distributionValue
        - distributionOrder
        