openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 4.0.1
  title: RFP
  description: Allows the buyer to submit a Request for Proposal (RFP) to the seller with overall media budget, goal and makegood terms and optionally include specific detailed inventory requests 
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /rfp:
    post:
      summary: Create an RFP in the seller's system
      description: |
        Create an RFP in the seller's system
      operationId: createRfp
      requestBody:
        description: Create an RFP in the seller's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPRequestBodyParameters'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPResponse'
              examples:
                RFPResponse:
                  $ref: 'examples/rfpExamples.yaml#/components/examples/RFPResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
    patch:
      summary: Change the details of a RFP in the seller's system
      description: |
        Change the details of a RFP in the seller's system
      operationId: updateRfp
      requestBody:
        description: Change an RFP in the seller's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPRequestBodyParameters'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPResponse'
              examples:
                RFPResponse:
                  $ref: 'examples/rfpExamples.yaml#/components/examples/RFPResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
    delete:
      summary: Cancel a specific RFP in the seller's system
      description: |
        Cancel a specific RFP in the seller's system
      operationId: cancelRfp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPRequestBodyParameters'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/rfpSchemas.yaml#/components/schemas/RFPResponse'
              examples:
                RFPResponse:
                  $ref: 'examples/rfpExamples.yaml#/components/examples/RFPResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'