openapi: "3.0.0"
components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []
info:
  version: "4.2.0"
  title: Inventory Avails
  description: Inventory Endpoints
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /buyer/inventoryAvails:
    post:
      summary: Send the request for the inventory avails required
      description: This endpoint is hosted at the seller end, Allows the Buyer as part of campaign planning to initiate an Inventory Request to Seller
      operationId: inventoryAvailsBuyers
      requestBody:
        description: Send the request for the inventory avails required
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsBuyerRequestObject'
      responses:
        '200':
          description: Request processed successfully. Response is provided synchronously 
          content:
            application/json:
              schema:
                $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsSellerResponseObject'
        '202':
          description: Request was accepted, Response will be provided asynchonously.
          content:
            application/json:
              schema: 
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: unexpected error, return the appropriate and corresponding HTTP status code matching the error 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /seller/inventoryAvails:
    post:
      summary: Seller POSTs the the Inventory Avails information to the buyer's system
      description: > 
        This endpoint will be hosted at the buyer side, 
        Allows the Seller to send inventory criteria such as Stations, Selling Elements, Inventory Types, Pricing, Audience Estimates 
        either solicited or unsolicited
      operationId: inventoryAvailsSellers
      requestBody:
        description: Seller POSTs the the Inventory Avails information to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/inventoryAvailsSchemas.yaml#/components/schemas/inventoryAvailsSellerResponseObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/AcceptedResponse'
        default:
          description: unexpected error, return the appropriate and corresponding HTTP status code matching the error 
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
