openapi: "3.0.0"
components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 0.0.1.
  title: Invoice
  description: Allows the seller to send to the buyer both new and revised invoice information
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /seller/invoice:
    post:
      summary: Allows the seller to send to the buyer new invoice information (No Request from buyer is Required)
      description: Allows the seller to send to the buyer new invoice information
      operationId: invoicePostSeller
      requestBody:
        description: Invoice body included in request
        required: true
        content:
          application/json:
            schema:
              oneOf:
              - $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
              - $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/creditMemoObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                oneOf:
                - $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/invoiceObject'
                - $ref: 'schemas/invoiceSchemas.yaml#/components/schemas/creditMemoObject'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'