openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 1.0.0
  title: logTimes
  description: Seller posts a Logtimes on the buyer's server.
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /logs/times/buyer:
    post:
      summary: Request for pre and/or post air date and times
      description: buyer's system POSTs a Log Times request to seller's system
      operationId: logsTimesBuyer
      requestBody:
        description: buyer's system POSTs a Log Times request to seller's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/logTimesBuyerObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/LogTimeResponseResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

      callbacks:
        sellerPostCallback:
          '{$request.body#/callbackUrl}':
            post:
                requestBody:   # Contents of the callback message
                  required: true
                  content:
                    application/json:
                      schema:
                        $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/logTimesSellerObject'
                responses:   # Expected responses to the callback message
                  '200':
                    description: Request processed successfully
                    content:
                      application/json:
                        schema:
                          $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/LogTimeResponseResponse'
                  default:
                    description: unexpected error
                    content:
                      application/json:
                        schema:
                          $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
  /logs/times/seller:
    post:
      summary: seller POSTs the Log Times report to the buyer's system
      description: Allows the seller to send to the buyer the log times information (No Request from buyer is Required)
      operationId: logsTimesSeller
      requestBody:
        description: seller POSTs the Log Times report to the buyer's system
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/logTimesSellerObject'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/logTimesSchemas.yaml#/components/schemas/LogTimeResponseResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
