openapi: "3.0.0"
info:
  version: 4.0.1
  title: RFP Schemas
  description: RFP Schemas, based on TIP 4.0.0 documentation
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Forum
    email: tip-mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths: {} # no paths

components:
  schemas:
    RFPRequestBodyParameters:
      required:
        - transactionHeader
        - RFPId
        - RFPVersion
        - RFPName
        - dateSubmitted
        - buyerLocation
        - Advertiser
        - Contact
        - mediaType
        - Budget
        - audienceMetric
        - dateStart
        - dateEnd
        - timeFrame
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/transactionHeader'
        RFPId:
          description: Buyer-generated unique identifier for the RFP
          type: string # TODO any constraints?
        RFPVersion: 
          description: todo # TODO missing description
          type: string # TODO any constraints?
        RFPName:
          description: RFP Name
          type: string # TODO any constraints?
        dateSubmitted:
          description: Buyer Submit Date for the RFP
          type: string
          format: date-time
        dueDate:
          description: Due Date for the Response
          type: string
          format: date-time
        buyerLocation:
          $ref: 'commonSchemas.yaml#/components/schemas/buyerLocation'
        Advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        Brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        Product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        Currency:
          description: Currency
          type: string # TODO change this to an enum
        Contact:
          description: Contact Information who initiated the RFP
          $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        mediaType:
          description: Types of media being requested in the RFP 
          type: string
          enum: [Linear Television, OTT]
        mediaOutlet:
          description: List of unique identifiers for individual station or network
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/mediaOutlet'
        Budget:
          description: Total Budget 
          type: number
          format: float
        audienceMetric:
          description: Pricing metric  (CPM, CPP, etc.)
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Audience'
        Commission:
          description: Buyer Commission percentage amount 
          type: number
          format: double
        Geographic:
          description: Specific market or geo target areas 
          type: string # TODO any constraints?
        daypartPreferences:
          description: List of dayparts preferences
          type: array
          items:
            type: string # TODO any constraints?
        unitLengthPreferences:
          description: List of unit length preferences
          type: array
          items:
            type: string # TODO any constraints?
        programPreferences:
          description: List of program preferences
          type: array
          items:
            type: string # TODO any constraints?
        dateStart:
          description: Start Date
          type: string
          format: date-time
        dateEnd:
          description: End Date
          type: string
          format: date-time
        hiatusPeriod:
          description: List of hiatus broadcast dates not valid for campaign
          type: array
          items:
            type: string
            format: date-time
        timeFrame:
          description: List of valid start and end times 
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/timeFrame'
        revenueType:
          description: Revenue Type
          type: string
          enum: [Cash, Barter, Trade, Custom] # TODO Custom is ambigious
        dayGuidelines:
          description: List of day and time exclusions 
          type: array
          items:
            type: string
            format: date-time
        MPAAGuidelines:
          description: List of MPAA exclusions 
          type: string
          enum: [TV-Y, TV-Y7, TV-G, TV-PG, TV-14, TV-MA]
        Objective:
          description: KPI of the overall campaign 
          type: string #TODO any constraints?
        Comments:
          description: Additional Information
          type: string #TODO any constraints?
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the TIP flow
          type: string #TODO any constraints?    

    RFPResponse: # TODO stub response, needs to be defined
      description: Response data # TODO stub response, needs to be defined
      properties:
        transactionId:
          type: string
        transactionDate:
          type: string